### ISSUE TITLE
Eximchain Integration - Governance

### ISSUE THREAD

**Issue by Lsquared13** [Eximchain/quorum#6]
# Issue

We need to integrate the Eximchain governance contract. This may require work in the [quorum-genesis repository](https://github.com/Eximchain/quorum-genesis) as well.

# Acceptance Criteria

- We have integrated the Eximchain governance contract and tested it by running a test network

**Comment by john-osullivan** [comment]
This issue is now nearly wrapped up, my bad on not documenting work more thoroughly as it went. 

## Prior Work

Previously, I wrote up an [`IdentityRegistry`](https://github.com/john-osullivan/eximchain-governance-mechanism/blob/master/contracts/EximchainIdentityRegistry.sol) contract which lets users apply for governance.  It essentially acts as an owner-managed state machine letting addresses register and eventually get approved to govern in our network.  A more thorough description of the transitions is available on the [original IdentityRegistry issue](https://github.com/Eximchain/eximchain-notes/issues/7).

## Completed Work

With this `IdentityRegistry` complete, I moved on to completing its integration with the existing [`WeylGovernance`](https://github.com/john-osullivan/eximchain-governance-mechanism/blob/master/contracts/WeylGovernance.sol) contract.  I added:
- checks that only ApprovedGoverning addresses ever participate in voting
- an `executeGovernance()` fxn which calls `BlockVoting` consensus contract to update BlockMakers upon completing a governance cycle
- new `findWinner()` fxn which iterates over all nominees in cycle to definitively check who won, fixing a bug in previous implementation
- a number of gas optimizations, incl. minimizing struct sizes and preventing array resize costs
- new tests for addt'l fxns, also added many helpers to make test suite clearer & reduce boilerplate
- modified `BlockVoting`'s `addMaker`/`removeMaker` fxns to require that they be called from our governance contract

I also did some exploratory testing on the gas cost of finalizing a governance cycle as the number of nominees increases.  Finding the winner requires iterating over every nominee in the cycle, so the gas cost eventually gets prohibitive.  Did some optimization and testing, found that it scales pretty linearly and the cost hits millions once you're in the thousands of nominees -- capped the total nominees per cycle at 1024.

Last step was popping these babies into a genesis block so we can run them on a real network.  Did some work to verify what Solidity versions we can deploy on based on where our fork from geth is at; we can handle up `Solidity@0.4.11`, which corresponds to `Truffle@3.2.2`.  Recompiling on that version required updating a few things here and there, but eventually worked.  I forked our `quorum-genesis` into [`john-osullivan/exim-genesis`](https://github.com/john-osullivan/exim-genesis), it now preloads our governance contract into address `0x0000000000000000000000000000000000000042` and uses a `governanceOwners` key in the config file to preset some owning addresses. 

## Remaining Work

This is nearly wrapped up now.  First I'm going to try running the 7nodes example with a genesis block generated from my new script, see that baseline Quorum behaves even after performing mild modifications to the source (and therefore the bytecode).  Once that's working, I'll swap the new genesis generator into `terraform-aws-quorum-cluster` and try launching a test net with governance up and running.  Once that all behaves, this issue should be ready to wrap!

**Comment by john-osullivan** [comment]
This is now essentially complete!  Didn't bother with 7nodes, but got everything loaded up into the new genesis block.  There are four different PRs because of all the moving parts:
- [eximchain-governance-mechanism: Code Review](https://github.com/Eximchain/eximchain-governance-mechanism/pull/2) - This contains all of the `IdentityRegistry`, `WeylGovernance`, `BlockVoting` source contracts.  It's already been reviewed, only changes since then were creating `Deployable` versions which referred to hard-coded genesis block addresses rather than accepting arguments used for running tests.
- [terraform-aws-quorum-cluster: Governance Integration](https://github.com/Eximchain/terraform-aws-quorum-cluster/pull/48) - Adds `owners` arg to `generate-quorum-config.py`
- [quorum: BlockVoting changes](https://github.com/Eximchain/quorum/pull/17) - Replaces the BlockVoting contract and related files which are hard-coded into Quorum.
- [quorum-genesis: WeylGovernance modifications](https://github.com/Eximchain/quorum-genesis/pull/1) - Adds the `WeylGovernance` bytecode to genesis template, modifies `index.js` to build the new storage.

**Comment by john-osullivan** [comment]
The final draft of this code has been shipped off to the auditors as of last week.  I don't have permission to close this issue, but the only remaining work on it will be known once the auditors get back to us on Sep21 with a changelog.  

For the sake of not leaving things outstanding too long, we could just make another issue for that when it comes in -- up to you, @Lsquared13

**Comment by Lsquared13** [comment]
Yep, closing this issue, and we'll need to open issues to address pretty much everything auditors tell us
